### ISSUE TITLE
Script gets rid of potions, super potions and razzberries 

### ISSUE THREAD

**Issue by vmunich** [j-e-k/pgoapi#1]
Right after using the script, all potions, super potions and razzberries were gone. Hyper potions were not affected.

Edit: I'm sorry I just realized this was intended by looking at pgoapi.py.

**Comment by j-e-k** [comment]
Ya, I added that because it was running out of pokeballs....If you want to disable it it is pretty easy, see `BAD_ITEM_IDS` in `pgoapi.py`

**Comment by vmunich** [comment]
Yep I did it :) thanks for the script!
