### ISSUE TITLE
Requirements wont install

### ISSUE THREAD

**Issue by Clintoxen** [j-e-k/pgoapi#101]
I keep getting
![error](https://cloud.githubusercontent.com/assets/20504430/17129526/9e2ed03c-52e1-11e6-9cf5-1f951c30f1e7.JPG)

When trying to installl the requirements 
I tried 
`pip install --upgrade setuptools` or `easy_install -U setuptools`

or

 `python ez_setup.py`
Just in case I was missing something. Havent came across this issue while using python before

**Comment by JavidPack** [comment]
I had the same. I think I just had to upgrade pip itself. 

If that isn't enough, I also installed the "Microsoft Visual C++ Compiler for Python 2.7".

**Comment by Clintoxen** [comment]
@JavidPack man I wish I posted this 2 and a half hours ago lol I just finnaly came across a website recommending me install that right before you posted lol. Well on the bright side I was bound to have to get that sooner or later working with Python, thanks.
