### ISSUE TITLE
[Request] Add a pokemon blacklist

### ISSUE THREAD

**Issue by MrHalfman** [j-e-k/pgoapi#103]
Hi, it would be nice to have the opposite of the KEEP_POKEMON_IDS parameter (something like `RELEASE_POKEMON_IDS`).

I'm tired of theses Pidgey, Drowzee and Rats. If they met the IVs and CPs requirements the bot keep them, which is the good behavior, but realasing them every time would be nice.

Thanks :smile:.

**Comment by MrHalfman** [comment]
Just saw that it was made in 37be671fec0ab25bc55b7af0817bba065a540ed1 ;). Thanks @joychugh, my config.json file wasn't updated.

**Comment by joychugh** [comment]
There is throw Pokemon ID

**Comment by MrHalfman** [comment]
Seems that it doesn't works as intended @joychugh. 

More, it seems that it keeps the pokemons stored in the array even if they don't met the IVs and CPs requirements.

I just got tons of Rattata and "RATTATA" is in "THROW_POKEMON_NAMES" array, many of them are 30% IV and my MIN_KEEP_IV is set at 65.

I just read the code but I can't manage to see if there is something wrong in it.

![selection_106](https://cloud.githubusercontent.com/assets/3469538/17143270/28362872-5353-11e6-8c89-0b5bbeb90c4f.png)

**Comment by joychugh** [comment]
let me check

**Comment by MrHalfman** [comment]
Thanks :smile:

**Comment by joychugh** [comment]
The thing is, we keep 1 pokemon in the list, so maybe that is your best pokemon so far. There is change recently to sort them by CV first since IV is not a stable method (since server does not send iV values all the time, so a good pokemon may have less IV because the server didn't send it)

**Comment by joychugh** [comment]
Earlier we used to sort by IV and then CP but we found out that IV was not being sent from server in some cases so it's unreliable we switched to CP

**Comment by MrHalfman** [comment]
Oh, I see, but in my opinion when you put a pokemon in "THROW_POKEMON_NAMES" it should release it automatically whether it's the best one or not. 

I thought it was working like this.

**Comment by joychugh** [comment]
no we want to keep atleast 1 :) unless yuou wantto throw all, 
do MIN_KEEP ... = 0 (but that will affect all pokemon)

**Comment by MrHalfman** [comment]
I see, I thought this parameter was working like "Release every pokemon in this list".

So, it works well :). Thanks for the answers.
