### ISSUE TITLE
[Missing] status/pokemon/***.png in web.py

### ISSUE THREAD

**Issue by MePsyDuck** [j-e-k/pgoapi#113]
While running webserver web.py, client issues a request "GET /static/pokemon/***.png HTTP 1.1" which is responded by server with code 304. Where are those missing files and do they have any use?

**Comment by MrHalfman** [comment]
Hi,

304 Response code is not an error, it just means `Not Modified`which is normal because you are reading the same static file multiple time and it just hits the cache.
Missing file would return a 404 response code.

**Comment by MePsyDuck** [comment]
Okay, but do they have any use?

**Comment by MrHalfman** [comment]
When you scroll down, you can see the pokemons' pictures in the table. It's just these pictures.

**Comment by j-e-k** [comment]
What he said

**Comment by MePsyDuck** [comment]
Oh sorry for such a noob question, I didn't see that. The readme needs to be updated!

**Comment by MrHalfman** [comment]
> The readme needs to be updated!

With what?

**Comment by MePsyDuck** [comment]
With details to use webserver. Also, you need to use your  google mail as directory not your username, which probably some will confuse with the game username.
