### ISSUE TITLE
Error in main loop, restarting Pokemon instance has no attribute '__getitem__'

### ISSUE THREAD

**Issue by stef264** [j-e-k/pgoapi#119]
I'm getting this error.
I have enough pokeballs.
> [ERROR] Error in main loop, restarting Pokemon instance has no attribute '__getitem__'

**Comment by j-e-k** [comment]
I assume you have restarted bot without --cached running, can you paste a full log with username redacted? Thanks

**Comment by j-e-k** [comment]
Also try pulling the latest version of the bot. Thanks

**Comment by stef264** [comment]
I have the latest version.
Same problem without --cached
> C:\Dev\j-e-k BOT>python pokecli.py -i 0 --cached
> 2016-07-26 18:58:18,346 [   pokecli] [ INFO] Your given location: ***
> 2016-07-26 18:58:18,348 [   pokecli] [ INFO] lat/long/alt: ***
> 2016-07-26 18:58:18,355 [  auth_ptc] [ INFO] Login for: ***
> 2016-07-26 18:58:19,085 [  auth_ptc] [ INFO] PTC Login successful
> 2016-07-26 18:58:19,086 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
> 2016-07-26 18:58:19,476 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
> 2016-07-26 18:58:19,479 [    pgoapi] [ INFO] Login process completed
> 2016-07-26 18:58:19,786 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316500, Pokemon Caught in this run: 0
> 2016-07-26 18:58:20,309 [    pgoapi] [ INFO] Player Items: PokeBalls: 30, GreatBalls: 51, MasterBalls: 0, UltraBalls: 78
>  Potion: 0, Super Potion: 10, Max Potion 20, Hyper Potion 10
> 2016-07-26 18:58:20,536 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316500, Pokemon Caught in this run: 0
> 2016-07-26 18:58:21,857 [    pgoapi] [ INFO] Walking to fort at  http://maps.google.com/maps?q=***
> 2016-07-26 18:58:22,088 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316500, Pokemon Caught in this run: 0
> 2016-07-26 18:58:22,730 [    pgoapi] [ INFO] Fort Spinned: http://maps.google.com/maps?q=***
> 2016-07-26 18:58:22,733 [    pgoapi] [ INFO] On my way to the next fort! :)
> 2016-07-26 18:58:24,026 [    pgoapi] [ INFO] Nearby Pokemon: Zubat
> 2016-07-26 18:58:24,029 [    pgoapi] [ INFO] Catching Pokemon: Zubat
> 2016-07-26 18:58:24,273 [    pgoapi] [ INFO] Player Items: PokeBalls: 33, GreatBalls: 51, MasterBalls: 0, UltraBalls: 78
>  Potion: 0, Super Potion: 10, Max Potion 20, Hyper Potion 10
> 2016-07-26 18:58:24,911 [    pgoapi] [ INFO] Caught Pokemon:  Zubat
> 2016-07-26 18:58:33,142 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316600, Pokemon Caught in this run: 1
> 2016-07-26 18:58:33,549 [    pgoapi] [ INFO] On my way to the next fort! :)
> 2016-07-26 18:58:34,816 [    pgoapi] [ INFO] No nearby pokemon
> 2016-07-26 18:58:35,082 [    pgoapi] [ INFO] No nearby pokemon
> 2016-07-26 18:58:35,312 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316600, Pokemon Caught in this run: 1
> 2016-07-26 18:58:36,798 [    pgoapi] [ INFO] Walking to fort at  http://maps.google.com/maps?q=***
> 2016-07-26 18:58:37,072 [    pgoapi] [ INFO] Username: ***, Currencies: POKECOIN: NA,STARDUST: 316600, Pokemon Caught in this run: 1
> 2016-07-26 18:58:37,101 [   pokecli] [ERROR] Error in main loop, restarting Pokemon instance has no attribute '__getitem__'

**Comment by AllesCoolAllesBestens** [comment]
If you revert the latest [commit](https://github.com/j-e-k/pgoapi/commit/9c4efe1c87e2427f2be0f6574f81a65884b9f003) it works again.

**Comment by j-e-k** [comment]
Gah, I need to add testing. Let me fix that now

**Comment by j-e-k** [comment]
Ya pull was merged into master instead of develop by mistake, go ahead and update and all should be well

**Comment by stef264** [comment]
Nice, thank you!
