### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by COLDPOKEMONGO** [j-e-k/pgoapi#120]
I'm currently encountering an error with I input the " pip install -r requirements.txt ".

The error is this: 
Command "python setup.py egg_info" failed with error code 1 in C:\ users...\appdata\local\temp\pip-build-sdj2gw\pyproj\

Not sure about what the error is about :/

Edit: 
It can't find the file that I am supposed to be downloading but I'm not sure which file this is supposed to be.

**Comment by j-e-k** [comment]
Can you post the full log? Thanks!

**Comment by COLDPOKEMONGO** [comment]
![error](https://cloud.githubusercontent.com/assets/20595366/17148932/fd269708-5360-11e6-9add-bd10aa6a4809.jpg)

**Comment by HibikiFox** [comment]
after googling around I found that Installing the Microsoft Visual C++ Compiler for Python 2.7 solved my issue for the requirements: https://www.microsoft.com/en-us/download/details.aspx?id=44266

however I am running into a separate issue when trying to run the bot, I will post a new issue with log.

**Comment by COLDPOKEMONGO** [comment]
@HibikiFox oh yeah that fixes the installation. cheers man. I was so confused with the error and didn't know what to search online.
