### ISSUE TITLE
Its worked fine at start, but having issues later

### ISSUE THREAD

**Issue by leovarmak** [j-e-k/pgoapi#14]
Hey !

This thing works like a charm. But later I get the failed to catch message all the time. What is wrong ? I tried multiple locations and always there is this failed to catch thing

**Comment by erhan-** [comment]
Might be softban if forts also don't work.

**Comment by j-e-k** [comment]
Do you have full pokemon bag, do you not have any pokeballs? If not, then you might be soft banned try again in an hour or two

**Comment by j-e-k** [comment]
Closing for now, please reopen if you still have problems
