### ISSUE TITLE
Docker container not working properly

### ISSUE THREAD

**Issue by Nemant** [j-e-k/pgoapi#15]
pgoapi-master $ docker build -t pokecli .
Sending build context to Docker daemon 3.162 MB
Step 1 : FROM python:3-onbuild
[....]
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libprotobuf9 libprotoc9
The following NEW packages will be installed:
  libprotobuf9 libprotoc9 protobuf-compiler
0 upgraded, 3 newly installed, 0 to remove and 7 not upgraded.
Need to get 709 kB of archives.
After this operation, 2522 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c apt-get update && apt-get install protobuf-compiler' returned a non-zero code: 1
pgoapi-master $ ls
Dockerfile                   MANIFEST.in                  config.json.example          old-demo                     pokemon.en.json              static
GAME_MASTER_POKEMON_v0_2.tsv README.md                    data_dumps                   pgoapi                       requirements.txt             templates
LICENSE.txt                  compile_proto.sh             examples                     pokecli.py                   setup.py                     web.py
pgoapi-master $ docker run pokecli
Unable to find image 'pokecli:latest' locally
Pulling repository docker.io/library/pokecli
docker: Error: image library/pokecli:latest not found.
See 'docker run --help'.
pgoapi-master $

**Comment by Nemant** [comment]
The issue is that on my mac I don't have apt-get. Will try to fix this on the Docker build

**Comment by j-e-k** [comment]
Alright closing for now then... let me know if you still have problems
