### ISSUE TITLE
python web client not working

### ISSUE THREAD

**Issue by ZohaibMKhan** [j-e-k/pgoapi#16]
data_dumps gets the file which is named after your email e.g. myemail@gmail.com.json

However the web client looks for username.json file

IOError: [Errno 2] No such file or directory: u'data_dumps/username.json'

simple fix would be to look for email instead of user

**Comment by ZohaibMKhan** [comment]
note: i renamed my json file and it works, working on the fix

**Comment by ZohaibMKhan** [comment]
fixed

on line 174:
`
with open("data_dumps/%s.json" % player_data.get('username', 'NA'), "w") as f:
`

**Comment by j-e-k** [comment]
you should be able to access the web client from `http://127.0.0.1:5000/ myemail@gmail.com/pokemon`

Does that not work for you?

**Comment by ZohaibMKhan** [comment]
no, i tried and it didnt work, maybe i was doing something wrong but the fix would make life easier

**Comment by joychugh** [comment]
you can login into google account without giving your @gmail.com suffix too so the username is simpler . @ZohaibMKhan

**Comment by kifki** [comment]
Hi,
I'm trying to use the web client, but I just can't connect to the server.
Any suggestions?
Thank you

**Comment by joychugh** [comment]
@kifki  please open an issue with your question we will try to help. and let us know what steps did you try.
