### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by leovarmak** [j-e-k/pgoapi#2]
Hey !
 I edited the `config.json` as per my requirements . I changed the `ACCOUNT_INDEX` to 0 . Now the this the error I get. Please help me 
![screen shot 2016-07-21 at 6 55 08 pm](https://cloud.githubusercontent.com/assets/14135553/17024323/23bfa778-4f75-11e6-8229-0cc75b798e23.png)

**Comment by j-e-k** [comment]
Try pulling the latest version, I included `protobuf_to_dict.py` rather than have it be installed. If it still doesn't work please go ahead and post the new error

**Comment by leovarmak** [comment]
I pulled it just now again on my local computer. This is the issue I get now

![screen shot 2016-07-22 at 10 25 22 am](https://cloud.githubusercontent.com/assets/14135553/17047010/e22aa68c-4ff6-11e6-8b52-bbd007138578.png)

**Comment by j-e-k** [comment]
try again now with latest version and let me know what happens

**Comment by leovarmak** [comment]
@j-e-k  Haha. Alright

**Comment by Aiyubi** [comment]
@j-e-k got the same issue and it seems to be a bad formated file in the api you forked. Have a look at rpc_api.py line 36 and see for yourself

**Comment by Aiyubi** [comment]
@j-e-k found a solution. In requirements.txt remove the hash before the egg

**Comment by j-e-k** [comment]
Is this still not working? I rebased but it was a bit of a messy merge.

**Comment by Aiyubi** [comment]
@j-e-k works for me now !
