### ISSUE TITLE
Improve Auto Evolve

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/pgoapi#25]
When you have a bunch of candy for a bad pokemon, you might as well evolve it before xfer to more xp

**Comment by joychugh** [comment]
doesn't it happen alredy? 
`2016-07-25 03:09:54,154 [    pgoapi] [ INFO] Evolving pokemon: Nickname: , Type: Pidgey, CP: 43, IV: 40.0
2016-07-25 03:09:57,459 [    pgoapi] [ INFO] Evolved to Nickname: , Type: Pidgeotto, CP: 82, IV: 40.0` 

`2016-07-25 01:43:58,961 [    pgoapi] [ INFO] Evolving pokemon: Nickname: , Type: Zubat, CP: 211, IV: 35.5555555556
2016-07-25 01:44:02,228 [    pgoapi] [ INFO] Evolved to Nickname: , Type: Golbat, CP: 687, IV: 35.5555555556`

**Comment by joychugh** [comment]
I think i pushed an update last night, it should fix it i guess. let me know if you have something else in mind.

**Comment by Qatrame** [comment]
I think he is referring to the pgoapi.py line 69,70 and 71

**Comment by joychugh** [comment]
@Qatrame i have zubat and drowzee it works :)

**Comment by CyriouslyDylan** [comment]
I would recommend maybe building in an algorithm like pidgeycalc.com has. It calculates how many evolutions you can do during the duration of a lucky egg, and tells how how many of each you should keep and send candies back for. It's one of the best ways to level up, and evolving the pokemon as you get them would be a waste.

**Comment by joychugh** [comment]
We evolve WAY faster than the app does, to make a lucky egg work we would have to have A TON of pidgey,, i think we take what like 3 seconds b/w each evolve given egg is 30 minutes we need 600 pidgey to make use of lucky egg. :) the bot farms up levels pretty fast guys, you can use lucky egg when you use the account on your phone to maybe really play the game some time :)
