### ISSUE TITLE
Stay within a certain range of start

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/pgoapi#29]
Add a feature to stay within X meters of your starting location (for people that want to farm something)

**Comment by wesselvdv** [comment]
I actually already build something similar for this pgoapi a few days back. I would suggest that if no PokéStop can be found with the range, you should walk back to the origin (Initial location). That's how I had programmed it.

**Comment by joychugh** [comment]
@wesselvdv i had that in mind to keep last x locations in a stack and when out of locations, walk back, didn't get time to implement.

**Comment by wesselvdv** [comment]
Also implemented in #69

**Comment by wesselvdv** [comment]
Whoops, meant #63. On phone atm. Can't edit comment.
