### ISSUE TITLE
Allow binding on 0.0.0.0

### ISSUE THREAD

**Issue by thomasvt1** [j-e-k/pgoapi#31]
Allow binding on 0.0.0.0 for use on remote machines (vps's for example) instead of 127.0.0.1

**Comment by wesselvdv** [comment]
You can do this easily by editing the web.py:

Change this:
 ''if __name__ == "__main__":
    app.run(debug=True)''

To this:
''if __name__ == "__main__":
    app.run(host='0.0.0.0',debug=True)''

**Comment by j-e-k** [comment]
Is anyone against making this the default?

**Comment by wesselvdv** [comment]
by all means, make it default!

**Comment by Jay1** [comment]
This is a great idea, I was thinking about access it over remote machine too

**Comment by j-e-k** [comment]
Alrighty, listening on all addresses is now the default :)
