### ISSUE TITLE
Feature: Maximize Evolution Benefits

### ISSUE THREAD

**Issue by ambasta** [j-e-k/pgoapi#34]
Given that pidgies take 12 pokemon to evolve, and it would take roughly 60 pidgeys to maximize the benefit from lucky eggs, ideally pgoapi should not discard or level up any pidgeys depending on the candies available.

For example I've got 10 pidgeys and 50 candies, then I should hold ceil(50/12) = 5 pidgeys and transfer 5.

A better forumation would be,
x pokemons of some class, evolving at m candies each while y candies are available.

Then number of pokemons to transfer = z, implies

x-z = ceil((y+z)/m)

or 

(mx - y)/(m+1) >= z >= (m(x-1) -y)/(m+1)

Again taking the above example,

m = 12, x = 10, y = 50

=> (120 - 50)/13 >= z >= (108 - 50)/13
=> 5.38 >= z >= 4.46
Given z is integral.
Thus z = 5 and only 5 pidgeys should be discarded.

**Comment by joychugh** [comment]
just made an update recently, where we evolve as many pidgey's as possible and then discard any remaining. WIll add a feature (check issues) to discard whole families soon.

**Comment by wesselvdv** [comment]
Interesting equation, tried to put it in myself but I am not that proficient in Python.

**Comment by joychugh** [comment]
If we evolve as many as we can and transfer the rest, in the next subsequent runs, we will have enough candies to do a second evolution. so we just need to evolve first and transfer second (what it does now)

**Comment by wesselvdv** [comment]
@joychugh Very true, but right now you get errors because it's trying to release pokémon that were evolved moments before that. I would then suggest a better mechanism to release/evolve pokémon, this can either be somehow flag/remove pokemon that have been evolved before transfering, or transfer first (but not those that will be evolved) and evolve after.

**Comment by joychugh** [comment]
You are right, please create a bug issue. for this.

**Comment by ambasta** [comment]
Hi,

The idea is not to evolve pidgeys immediately but to hoard them until a sufficient large number to justify use of lucky eggs has been collected.

**Comment by wesselvdv** [comment]
That's pretty advanced. Are we even able to use items using the pgoapi?

**Comment by joychugh** [comment]
@ambasta This will take time. It's definitely not the most critical feature. The bot already levels up pretty fast.
