### ISSUE TITLE
Bag full bug

### ISSUE THREAD

**Issue by frosty1077** [j-e-k/pgoapi#35]
Seems like my pokemon bag is full despite the fact that most pokemon are under 400CP and yes I have set the threshold above this limit so surely the bot should at least be transferring the duplicates?

**Comment by joychugh** [comment]
do you have set an IV %

**Comment by frosty1077** [comment]
Yes this appears to be the issue, I feel like there needs to be a trash class of pokemon that are discarded regardless of their CP/IV values, or a way to set a different threshold for these type of pokemon.

**Comment by joychugh** [comment]
already added an enhancement request for that.

**Comment by joychugh** [comment]
@frosty1077 https://github.com/j-e-k/pgoapi/issues/39
