### ISSUE TITLE
How to release evolved pokemon?

### ISSUE THREAD

**Issue by uzbekki** [j-e-k/pgoapi#38]
I figured out how to add zubat to the evolve cycle, but now I have inventory full of golbats.
How do I make it so it transfers the golbat?

**Comment by joychugh** [comment]
well if ur CP cutoff is set higher it can discard golbats, and keep just 1

**Comment by uzbekki** [comment]
Well, I would like to keep the 700+ eevees, but discard the golbats that are all like 1000+
