### ISSUE TITLE
Move items to keep & pokemon to evolve into config.json

### ISSUE THREAD

**Issue by wesselvdv** [j-e-k/pgoapi#40]
I would like to be able to configure the items that I want to keep, and their respective amount inside the config.json. Same goes for the pokemon whom I want evolved.

**Comment by adrianocr** [comment]
@wesselvdv is this the original bot that tomthebotter forked?

**Comment by venounan** [comment]
@adrianocr yes

**Comment by adrianocr** [comment]
@venounan good to know. I'll start putting work into this one instead. Sorry for the random talk in an unrelated issue.

**Comment by wesselvdv** [comment]
@adrianocr Yes it is! Welcome, :-)

**Comment by wesselvdv** [comment]
Fixed this myself, @j-e-k close when develop is merged back?

**Comment by joychugh** [comment]
fixed
