### ISSUE TITLE
Issues Building Docker Image

### ISSUE THREAD

**Issue by gomsec** [j-e-k/pgoapi#41]
I am fairly new to using docker.  When I try to build this I am getting the following error.

Collecting expiringdict==1.1.3 (from -r requirements.txt (line 10))
  Downloading expiringdict-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-scv7w0vs/expiringdict/setup.py", line 2, in <module>
        import md5  # fix for "No module named _md5" error
    ImportError: No module named 'md5'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-scv7w0vs/expiringdict/
INFO[0018] The command [/bin/sh -c pip install --no-cache-dir -r requirements.txt] returned a non-zero code: 1

**Comment by j-e-k** [comment]
The docker build was contributed by someone else, I will take a look at it myself today and see what's up

**Comment by joychugh** [comment]
weird, what python are you using? and what system?

**Comment by gomsec** [comment]
I have python 2.7.6 currently installed.  This is on an Ubuntu 14.04 server.

**Comment by spamfarm** [comment]
Submitted PR that fixes this:
https://github.com/j-e-k/pgoapi/pull/83

**Comment by j-e-k** [comment]
Merged! Thanks for the contribution
