### ISSUE TITLE
Issue with web client: can't connect

### ISSUE THREAD

**Issue by kifki** [j-e-k/pgoapi#43]
Hello,
when I run the bot I'm having issues with the web client.
When I try to connect, the browser always gives the same "can't connect to the server" error.
The bot works well, so maybe I have some configuration problem.
Any suggestion?
Thanks

**Comment by wesselvdv** [comment]
Did you start the web.py?

**Comment by kifki** [comment]
Sorry, I'm new to python. Now it works :)
Thank you!
