### ISSUE TITLE
BUG: Evolve pokémon results in errors in transfer. (Tries to transfer evolved pokémon)

### ISSUE THREAD

**Issue by wesselvdv** [j-e-k/pgoapi#44]
Right now you get errors because it's trying to release pokémon that were evolved moments before that. I would then suggest a better mechanism to release/evolve pokémon, this can either be somehow flag/remove pokemon that have been evolved before transfering, or transfer first (but not those that will be evolved) and evolve after.

**Comment by joychugh** [comment]
Fix in devleop branch, will mergeto master after testing. a few minutes.
