### ISSUE TITLE
Feature Request:  CLI to interact with bot

### ISSUE THREAD

**Issue by ambasta** [j-e-k/pgoapi#45]
Hi,

It would be great if one could interact w/ the bot over CLI, such as using certain items, ask bot to move to a certain location gradually etc

Would need a server client model with the cli connecting to the bot server over sockets maybe?

**Comment by wesselvdv** [comment]
Interactive shell?

**Comment by ambasta** [comment]
Yes

**Comment by j-e-k** [comment]
I think I am going to do this over a web api instead to make it more robust
