### ISSUE TITLE
BUG: Recycle item new_count not there when item is removed.

### ISSUE THREAD

**Issue by wesselvdv** [j-e-k/pgoapi#48]
Recycle item new_count not there when item is removed.

```python
{'result': 1}
```

**Comment by joychugh** [comment]
2016-07-25 12:09:17,034 [    pgoapi] [ INFO] Recycling Item_ID 701, item count 1
2016-07-25 12:09:17,286 [    pgoapi] [ INFO] Recycled Item 701, New Count: 10

can you please add some more information?

**Comment by wesselvdv** [comment]
I have some items that I don't want, so I have their count on 0. Seems that if you recycle items to the point that there aren't any left, the result does not contain new_count.

**Comment by joychugh** [comment]
fixed.
