### ISSUE TITLE
Master/Develop Both Failed Travis Ci?

### ISSUE THREAD

**Issue by freakyfreak87** [j-e-k/pgoapi#524]
As stated, but on a different note when the builds are up, I seen in the configs that the google credential login in the json is omitting things like fort caching and wander steps, but the PTC portion of the JSON for login has all the options, and I was curious as to why that was removed as options under the google login credentials.

**Comment by infinitewarp** [comment]
Regarding the broken builds, see https://github.com/j-e-k/poketrainer/issues/513

As for the config, the `config.json.example` is just that: an _example_, not a comprehensive set of all options. You should make appropriate changes to your own working `config.json` and just use the example as a guide for possible configuration options. If you want options like fort caching enabled for your Google account, then make add it in to your local copy; they're not exclusive to one account type or the other.

**Comment by rirze** [comment]
Just to clarify this for others, but along the way, we decided to have a config that easy for users to look at and setup their own config. However, this created problems as we introduced features that have config options that we want documented in `config.json.example`. As a compromise, we had the google account have minimal options, enough to setup and run the program, while the PTC account is comprehensive and lists all the possible switches. If you are comfortable enough with the program, then please, look at the advanced account as an instructional example, but we feel like first-time users should find the first example adequate and not be overwhelmed by the _all_ the options.

Sorry for necro-ing the thread, but I felt this should be clarified.

**Comment by freakyfreak87** [comment]
Ah, I never bothered to put together that config.json and config.py worked together lmao, "dumbass" ill be good to go from now on I think haha, as far as this ban wave goes though, I thought I may let you know, at least from my side, that my main of all things that I bot on hasnt been banned 
"yet" but I have never gone overboard I dont think, or i'm just lucky, I usually run the bot for no more than 5/6 hours, usually at night, at least 3/4 days a week, and I stay usually close to home and farm one spot about 5 hours from me, and after closing the bot I usually waited the rest of the day before I would play in my hometown, and i've gone from level 18 to 33 using the bot usually using around a step limit of 70, and never using sniping etc, and so far my main is going strong.
