### ISSUE TITLE
Feature Request: Cleaning the Pokebox

### ISSUE THREAD

**Issue by holaygrail** [j-e-k/pgoapi#53]
Often the bot fails to release pokemon so the pokebox fills up after some time.
A script for cleaning the pokebox would be helfpul.

Maybe it could exclude favourite pokemon from releasing.

**Comment by joychugh** [comment]
Already excludes favorite
Why does the bot fail to release pokemon? exception? can you change logging to debug (in pgoapi.py) and print the output. 
If you have too many pokemon, maybe they are not meeting the CP threshhold you set (or IV) 
We will add feature to delete pokemon of a family no matter a CP or IV. for now try to increase the CP cutoff and IV cutoff to 1000, 90

**Comment by holaygrail** [comment]
`if pokemon.iv < self.MIN_KEEP_IV and pokemon.cp < self.KEEP_CP_OVER and pokemon.is_valid_pokemon()`

this is the check for releasing a pokemon

if the pokemons iv is bigger than `MIN_KEEP_IV` but the cp is lower, the bot will keep the low cp pokemon...
