### ISSUE TITLE
Feature suggestion: Output pokemon list to csv for easy viewing/sorting

### ISSUE THREAD

**Issue by adrianocr** [j-e-k/pgoapi#58]
I actually tried to do it myself but I'm not very good at working with lists in python. I see that get_inventory_data() is handling the pokemon list output but I couldn't figure out how to parse it into a CSV. 

This would be useful for quick glancing and if you use Excel to convert the CSV into a table you can do all kinds of things like sorting by IV, color coding certain pokemon, sorting by quantity, etc.

**Comment by joychugh** [comment]
@adrianocr the web api update recently has a ton of useful features like you suggest. check it out :)

**Comment by adrianocr** [comment]
@joychugh huh, would you look at that! Neat! Closing this issue
