### ISSUE TITLE
Request: Display info, stats, inventory also when closing bot (CTRL-C)

### ISSUE THREAD

**Issue by obmit2** [j-e-k/pgoapi#589]
Display the stats of the account at close like it is done at startup:

[poketrainer] [ INFO] Player Info: XYZ, Currencies: POKECOIN: NA,STARDUST: 123456, Pokemon Caught in this run: 24, forts spun: 24
[poketrainer] [ INFO] Player Stats: Level: 32, XP: 3445345/3750000, Runtime (h): 0.34, XP/h: 21259.0, Pokedex: 132, km walked: 56.70
[poketrainer] [ INFO] Player Inventory: PokeBalls: 24, GreatBalls: 10, UltraBalls: 24, MasterBalls: 0 
 Potion: 1, Super Potion: 1, Max Potion 24, Hyper Potion 7, Lucky Eggs 3, Razz Berries 69

**Comment by mhofer117** [comment]
this was a very small addition, check out the latest dev-branch and report back / close if applicable

**Comment by obmit2** [comment]
Great, thanks a ton!
