### ISSUE TITLE
Web.py works but only displays starting location on map.

### ISSUE THREAD

**Issue by adrianocr** [j-e-k/pgoapi#60]
Based on the console output of web.py I'm assuming it's supposed to show pokemon, right? 

I see: 

```
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/092.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/103.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/022.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/073.png HTTP/1.1" 304 -
....
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/055.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/108.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/095.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/044.png HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2016 15:58:20] "GET /static/pokemon/018.png HTTP/1.1" 304 -
....
```

But it doesn't actually display on the map. Chrome's dev console shows several `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` errors. The bot is working so it can't be my gmaps key. And the web view shows my entire list of pokemon and my data, etc. 

Running on `127.0.0.1:5000/MY_PERSONAL_USERNAME/pokemon`

**Comment by beeedy** [comment]
I have found that you need to let the bot runs for a couple minutes the first time it is run. Also, the page does not keep up to date with the bot so you must manually refresh the page.

**Comment by j-e-k** [comment]
This behavior will be improved in an upcoming update that features a more powerful web api....

**Comment by adrianocr** [comment]
@j-e-k roger that. I have a few ideas I'm going to work on and hopefully submit pull requests for. Thanks!
