### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by MrHalfman** [j-e-k/pgoapi#61]
Hi,

When I try to run pokecli.py I get the following error : 

> Traceback (most recent call last):
>   File "pokecli.py", line 136, in <module>
>     main()
>   File "pokecli.py", line 122, in main
>     if not api.login(config.auth_service, config.username, config.password, config.cached):
>   File "/home/halfman/pgoapi/pgoapi/pgoapi.py", line 541, in login
>     if not self._auth_provider.login(username, password):
>   File "/home/halfman/pgoapi/pgoapi/auth_google.py", line 46, in login
>     login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
>   File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
>     return _perform_auth_request(data)
>   File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
>     headers={'User-Agent': useragent})
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

What can I do to fix this error? :disappointed: 

Thanks for your help and thanks for this awesome work :smile:

**Comment by j-e-k** [comment]
So that is caused by the requests library verifying google's ssl certificate. It sounds like you might be getting MITM'd. Do you have some sort of atypical network setup? Alternativley, if you don't care you can set `self._session.verify` in `rpc_api.py` to False and it should work (hide the problem)...

**Comment by MrHalfman** [comment]
I have a firewall that is a littble bit a _aggressive_, maybe it can cause this issue (I'm launching the script on a virtual machine on my server).

Thanks for the solution, I will try this.

**Comment by MrHalfman** [comment]
Update: Seems that the solution is not working :cry:, I'm getting the same error.

**Comment by j-e-k** [comment]
Can you run the following and let me know the output:

```
openssl version
python -c "import requests; requests.get('https://android.clients.google.com/auth')"
 export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt; python -c "import requests; requests.get('https://android.clients.google.com/auth')"
```

**Comment by MrHalfman** [comment]
Sure,

> openssl version
> OpenSSL 1.0.1k 8 Jan 2015

> python -c "import requests; requests.get('https://android.clients.google.com/auth')"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

> export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt; python -c "import requests; requests.get('https://android.clients.google.com/auth')"
> Returns nothing

Thanks for your help

**Comment by MrHalfman** [comment]
The bot started successfully with " export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt;" :smile:

Any idea on why do I need to put this?

**Comment by j-e-k** [comment]
Openssl problem as far as I can tell. Try updating openssl and all should be 👍 , reopen if you still have problems
