### ISSUE TITLE
Exempt certain pokemon types from cleanup?

### ISSUE THREAD

**Issue by Zyrixion** [j-e-k/pgoapi#62]
I think there should be the ability to exempt certain pokemon from the cleanup, regardless of cp/iv, like maybe you want it to not throw away a snorlax, or lapras, dragonite, etc.  Perhaps similar to the list for evolutions?  Something like that.

**Comment by j-e-k** [comment]
Would you prefer for this to be by family id or pokemon id (or both?)

**Comment by Qatrame** [comment]
By pokemon id we could keep 60 Pidgey or more just for the lucky egg power leveling

**Comment by Zyrixion** [comment]
Just the pokemon ID, in the case of dragonite, you would want to keep dragonites, but not necessarily care about keeping dratinis/dragonairs, you know?
