### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by venounan** [j-e-k/pgoapi#68]
I believe I got it all set up correctly, but when I try to run it I get:

```
Traceback (most recent call last):
  File "pokecli.py", line 136, in <module>
    main()
  File "pokecli.py", line 102, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 28 column 6 (char 877)
```

**Comment by j-e-k** [comment]
Your `config.json` file is probably malformed. Can you post a copy of it (With your username/password/location set to "" of course)

**Comment by venounan** [comment]
I don't know if this affects it but I took config.json.example and made a copy so it's still in the folder with the new file config.json.

But it looks like this:

`{"accounts" :
    [{
        "auth_service": "google",
        "username": "test@gmail.com",
        "password": "password",
        "location": "University of Southern California, Los Angeles, CA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "some api key here",
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 500,
        "STEP_SIZE": 100,
        "EXPERIMENTAL": true,
        "SKIP_VISITED_FORT_DURATION": 600,
        "SPIN_ALL_FORTS": true
    },
    {  "auth_service": "ptc",
        "username": "",
        "password": "",
        "location": "223 garden st, cambridge, MA",
        "USE_GOOGLE": true,
        "GMAPS_API_KEY": "",
        "MIN_KEEP_IV" : 50,
        "KEEP_CP_OVER": 500,
        "STEP_SIZE": 5,
        "EXPERIMENTAL": true,
        "SKIP_VISITED_FORT_DURATION": 500,
        "SPIN_ALL_FORTS": true
    },`

**Comment by j-e-k** [comment]
If that is your entire file it looks like you forgot to close the accounts array, so it should be 
```
{
   "accounts":[
      {
         "auth_service":"google",
         "username":"test@gmail.com",
         "password":"password",
         "location":"University of Southern California, Los Angeles, CA",
         "USE_GOOGLE":true,
         "GMAPS_API_KEY":"some api key here",
         "MIN_KEEP_IV":50,
         "KEEP_CP_OVER":500,
         "STEP_SIZE":100,
         "EXPERIMENTAL":true,
         "SKIP_VISITED_FORT_DURATION":600,
         "SPIN_ALL_FORTS":true
      },
      {
         "auth_service":"ptc",
         "username":"",
         "password":"",
         "location":"",
         "USE_GOOGLE":true,
         "GMAPS_API_KEY":"",
         "MIN_KEEP_IV":50,
         "KEEP_CP_OVER":500,
         "STEP_SIZE":5,
         "EXPERIMENTAL":true,
         "SKIP_VISITED_FORT_DURATION":500,
         "SPIN_ALL_FORTS":true
      }
   ]
}
```
instead

**Comment by venounan** [comment]
Wow, what a silly error. Thank you.
