### ISSUE TITLE
[Improvement] Too many logs in Info

### ISSUE THREAD

**Issue by joychugh** [j-e-k/pgoapi#7]
Suggestion to change the log levels to debug for most of the items, 
Add info logs such as 
Catching "Pokemon Name"
Player Level: 
Total Pokemon in Inventory:
..

**Comment by j-e-k** [comment]
Ya it is a bit of a mess, if you have the time a pull req would be much appreciated. Otherwise, I will add cleaner logs to the web interface first...

**Comment by j-e-k** [comment]
Thanks for the pull req!
