### ISSUE TITLE
Error starting bot since new config

### ISSUE THREAD

**Issue by nieuwefn** [j-e-k/pgoapi#77]
This is the traceback...

Traceback (most recent call last):
  File "pokecli.py", line 140, in <module>
    main()
  File "pokecli.py", line 102, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 30 column 3 (char 829)

**Comment by j-e-k** [comment]
Your `config.json` file is probably malformed. Can you post a copy of it (With your username/password/location set to "" of course)

**Comment by nieuwefn** [comment]
I have 2 seperate google accounts. Ive tried removing the changed evolutions and IDs, without fixing the problem though...
{
  "accounts": [
    {
      "auth_service": "google",
      "username": "",
      "password": "",
      "location": "40.780003, -73.971053",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "",
      "MIN_KEEP_IV": 70,
      "KEEP_CP_OVER": 500,
      "STEP_SIZE": 100,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 300,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 500,
      "MIN_ITEMS": {
        "ITEM_POTION": 1,
        "ITEM_SUPER_POTION": 1,
        "ITEM_HYPER_POTION": 1,
        "ITEM_MAX_POTION": 1,
        "ITEM_BLUK_BERRY": 1,
        "ITEM_NANAB_BERRY": 1,
        "ITEM_REVIVE": 1,
        "ITEM_MAX_REVIVE": 1,
        "ITEM_RAZZ_BERRY": 1
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12
		"WEEDLE": 12
		"CATERPIE": 12
		"ZUBAT": 50
		"RATTATA": 25
		"SPEAROW": 50
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_IDS": [130, 134, 137, 139, 141, 142, 143, 149]
    },    {
      "auth_service": "google",
      "username": "",
      "password": "",
      "location": "40.780003, -73.971053",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "",
      "MIN_KEEP_IV": 70,
      "KEEP_CP_OVER": 500,
      "STEP_SIZE": 100,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 300,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 500,
      "MIN_ITEMS": {
        "ITEM_POTION": 1,
        "ITEM_SUPER_POTION": 1,
        "ITEM_HYPER_POTION": 1,
        "ITEM_MAX_POTION": 1,
        "ITEM_BLUK_BERRY": 1,
        "ITEM_NANAB_BERRY": 1,
        "ITEM_REVIVE": 1,
        "ITEM_MAX_REVIVE": 1,
        "ITEM_RAZZ_BERRY": 1
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12
		"WEEDLE": 12
		"CATERPIE": 12
		"ZUBAT": 50
		"RATTATA": 25
		"SPEAROW": 50
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_IDS": [130, 134, 137, 139, 141, 142, 143, 149]
    },
    {
      "auth_service": "ptc",
      "username": "someusername",
      "password": "password",
      "location": "University of Southern California, Los Angeles, CA",
      "USE_GOOGLE": false,
      "MIN_KEEP_IV": 70
    }
  ]
}

**Comment by j-e-k** [comment]
You have malformed Json, (see pokemon evolution) try this:

```{
"accounts": [
{
"auth_service": "google",
"username": "",
"password": "",
"location": "40.780003, -73.971053",
"USE_GOOGLE": true,
"GMAPS_API_KEY": "",
"MIN_KEEP_IV": 70,
"KEEP_CP_OVER": 500,
"STEP_SIZE": 100,
"EXPERIMENTAL": true,
"SKIP_VISITED_FORT_DURATION": 300,
"SPIN_ALL_FORTS": true,
"STAY_WITHIN_PROXIMITY": 500,
"MIN_ITEMS": {
"ITEM_POTION": 1,
"ITEM_SUPER_POTION": 1,
"ITEM_HYPER_POTION": 1,
"ITEM_MAX_POTION": 1,
"ITEM_BLUK_BERRY": 1,
"ITEM_NANAB_BERRY": 1,
"ITEM_REVIVE": 1,
"ITEM_MAX_REVIVE": 1,
"ITEM_RAZZ_BERRY": 1
},
"POKEMON_EVOLUTION": {
"PIDGEY": 12,
"WEEDLE": 12,
"CATERPIE": 12,
"ZUBAT": 50,
"RATTATA": 25,
"SPEAROW": 50
},
"MIN_SIMILAR_POKEMON": 1,
"KEEP_POKEMON_IDS": [130, 134, 137, 139, 141, 142, 143, 149]
}, {
"auth_service": "google",
"username": "",
"password": "",
"location": "40.780003, -73.971053",
"USE_GOOGLE": true,
"GMAPS_API_KEY": "",
"MIN_KEEP_IV": 70,
"KEEP_CP_OVER": 500,
"STEP_SIZE": 100,
"EXPERIMENTAL": true,
"SKIP_VISITED_FORT_DURATION": 300,
"SPIN_ALL_FORTS": true,
"STAY_WITHIN_PROXIMITY": 500,
"MIN_ITEMS": {
"ITEM_POTION": 1,
"ITEM_SUPER_POTION": 1,
"ITEM_HYPER_POTION": 1,
"ITEM_MAX_POTION": 1,
"ITEM_BLUK_BERRY": 1,
"ITEM_NANAB_BERRY": 1,
"ITEM_REVIVE": 1,
"ITEM_MAX_REVIVE": 1,
"ITEM_RAZZ_BERRY": 1
},
"POKEMON_EVOLUTION": {
"PIDGEY": 12,
"WEEDLE": 12,
"CATERPIE": 12,
"ZUBAT": 50,
"RATTATA": 25,
"SPEAROW": 50
},
"MIN_SIMILAR_POKEMON": 1,
"KEEP_POKEMON_IDS": [130, 134, 137, 139, 141, 142, 143, 149]
},
{
"auth_service": "ptc",
"username": "someusername",
"password": "password",
"location": "University of Southern California, Los Angeles, CA",
"USE_GOOGLE": false,
"MIN_KEEP_IV": 70
}
]
}```

😄

**Comment by nieuwefn** [comment]
Thanks, working now!
