### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by huntergregal** [j-e-k/pgoapi#8]
Couple issues I'm having -

1. The docker base image appears to be missing protobuf-compiler
add to Dockerfile should fix that -> "RUN apt-get update && apt-get install protobuf-compiler"

2.  Protos bug? Probably from switching to Aeons

`python pokecli.py -i 0 `

`Traceback (most recent call last):
  File "./pokecli.py", line 37, in <module>
    from pgoapi import PGoApi
  File "/root/git/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/git/pgoapi/pgoapi/pgoapi.py", line 43, in <module>
    from pgoapi.location import *
  File "/root/git/pgoapi/pgoapi/location.py", line 6, in <module>
    from protos.RpcEnum_pb2 import *
ImportError: No module named RpcEnum_pb2
`

Looks good though other then these

**Comment by jeid64** [comment]
Copying the pyc from Tejado's for the Rpc files fixes this for me.

**Comment by j-e-k** [comment]
Fixed, Sorry about that the pyc was hiding the bug from showing up for me.

**Comment by huntergregal** [comment]
Insane response time haha. Cheers m8.
