### ISSUE TITLE
2016-07-25 22:50:10,301 [   pokecli] [ERROR] Error in main loop, restarting set_position() takes exactly 4 arguments (2 given)

### ISSUE THREAD

**Issue by adrianocr** [j-e-k/pgoapi#90]
Pulled latest changes about 15 mins ago and now I can't run it. Neither from the master nor dev branch. Created a brand new pull into a separate directory and I'm getting the same issue.

**Comment by joychugh** [comment]
looking into it.

**Comment by joychugh** [comment]
Fixed, I didn't catch it since I wasn't using the experimental features :) looks like you like living on the edge ;)

**Comment by Jay1** [comment]
_If I'm not mistaken, experimental is :true by default_
