### ISSUE TITLE
Evolution broken by latest version

### ISSUE THREAD

**Issue by Zyrixion** [j-e-k/pgoapi#94]
`    def is_pokemon_eligible_for_evolution(self, pokemon):
        return self.inventory.pokemon_candy.get(self.POKEMON_EVOLUTION_FAMILY.get(pokemon.pokemon_id, None),
                                                -1) > self.POKEMON_EVOLUTION.get(pokemon.pokemon_id, None) \
               and pokemon.pokemon_id in self.keep_pokemon_ids \
               and not pokemon.is_favorite \
               and pokemon.pokemon_id in self.POKEMON_EVOLUTION`

I am pretty sure that "and pokemon.pokemon_id in self.keep_pokemon_ids \" should not be there and is preventing all auto-evolutions (like pidgey, and anything else you put in the list to evolve), because you won't want to fill your box with pidgeys to be able to evolve them.

**Comment by joychugh** [comment]
If someone  wants to keep "x" pokemon without being evolved or transferred, they should be able to. Unless someone wants to evolve pidgey and and keep it at the same time.

**Comment by Zyrixion** [comment]
Yes, but then the code should be "and NOT pokemon.pokemon_id in self.keep_pokemon_ids \" in that case, because right now, it will ONLY evolve pokemon that are IN the keep list, as opposed to pokemon that are SPECIFICALLY NOT in the keep list.

**Comment by joychugh** [comment]
fixed. Thanks!
